### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by HUTTON9453** [HUTTON9453/instantnano-analysis#4]
## Problem to solve

可能會提供給客戶一個授權碼，讓使用者可以透過授權碼登入後，看到圖片但不能編輯，且只會看到屬於自己的。
## Tasks

- [ ] construct ER module
- [ ] login page
- [ ] generate Authorization code
- [ ] show result page
